<?php

namespace AppBundle\Repository;

/**
 * CaracRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaracRepository extends \Doctrine\ORM\EntityRepository
{

}
