<?php

namespace AppBundle\Repository;

/**
 * TestSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestSetRepository extends \Doctrine\ORM\EntityRepository
{

}
