<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends \Doctrine\ORM\EntityRepository
{

    public function findTenByUser(User $user)
    {
        $query = $this->createQueryBuilder('t')
            ->leftJoin('t.initiator', 'ti')
            ->leftJoin('t.defendant', 'td')
            ->where('ti.user=:id')
            ->orWhere('td.user=:id')
            //->andWhere('t.winner IS NOT NULL')
            ->setMaxResults('10')
            ->setParameter('id', $user->getId())
            ->orderBy('t.id', 'DESC')
            ->getQuery();

        $result = $query->getResult();

        return $result;
    }

    public function findTenByAdminUser(User $user)
    {
        $query = $this->createQueryBuilder('t')
            ->leftJoin('t.initiator', 'ti')
            ->leftJoin('t.defendant', 'td')
            ->where('t.initiator is NULL')
            //->orWhere('td.user=:id')
            //->andWhere('t.winner IS NOT NULL')
            ->setMaxResults('10')
            //->setParameter('id', $user->getId())
            ->orderBy('t.id', 'DESC')
            ->getQuery();

        $result = $query->getResult();

        return $result;
    }
}
