<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends \Doctrine\ORM\EntityRepository
{

    public function findDefending(User $user)
    {
        $query = $this->createQueryBuilder('t')
            ->join('t.defendant', 'td')
            ->where('td.user=:id')
            ->andWhere('t.winner is null')
            ->setParameter('id', $user->getId())
            ->getQuery();

        $result = $query->getResult();

        return $result;
    }


    public function findInitiating(User $user)
    {
        $query = $this->createQueryBuilder('t')
            ->join('t.initiator', 'ti')
            ->where('ti.user=:id')
            ->andWhere('t.winner is null')
            ->setParameter('id', $user->getId())
            ->getQuery();

        $result = $query->getResult();

        return $result;
    }

    public function findAllByUser(User $user)
    {
        $query = $this->createQueryBuilder('t')
            ->join('t.initiator', 'ti')
            ->join('t.defendant', 'td')
            ->where('ti.user=:id')
            ->orWhere('td.user=:id')
            ->andWhere('t.winner IS NOT NULL')
            ->setParameter('id', $user->getId())
            ->getQuery();

        $result = $query->getResult();

        return $result;
    }
}
