<?php

namespace AppBundle\Repository;

/**
 * UserCaracRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCaracRepository extends \Doctrine\ORM\EntityRepository
{

}
