<?php

namespace AppBundle\Repository;

/**
 * UserDisciplineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDisciplineRepository extends \Doctrine\ORM\EntityRepository
{
}
