<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function findCaracValue($value, $id)
    {
        $result = $this->createQueryBuilder('u')
            ->select('u.'. $value)
            ->where('u.id = :id' )
            ->setParameter( 'id', $id)
            ->getQuery()
            ->getSingleScalarResult();

        return $result;
    }

}
